language: python

python:
  - "3.6"

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - (cd src/test && PYTHONPATH=.. nosetests)

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./docker-release.sh
